
import java.io.IOException;
import java.io.RandomAccessFile;


public class Aplet1 extends java.applet.Applet {


    
   public void dopisz(int i, String s, double ocena){
        try{
            RandomAccessFile raf = new RandomAccessFile("plik.bin", "rw");
            
            long skok = raf.length();
            raf.seek(skok); // skok -  adres w bajtach
            
            raf.writeInt(i);
            raf.writeUTF(s); // zapis string
            raf.writeDouble(ocena);
            
            raf.close();
        }catch(IOException e){
            System.out.println("Błąd we/wy ");
       }
   }
    
   public  void odczyt(int skok, int ile){
           int i;
           String s;
           long miejsce;
           double ocena;
           
           
        try{
            RandomAccessFile raf = new RandomAccessFile("plik.bin", "rw");
            
           // raf.seek(skok); // skok -  adres w bajtach
           i=1;
           while(raf.getFilePointer() < raf.length() && i < skok){
                i = raf.readInt();
                s = raf.readUTF(); // odczyt string
                ocena = raf.readDouble();
                i++;
           } ;
           
            int licz=1;
            do{
                miejsce = raf.getFilePointer();
                i = raf.readInt();
                s = raf.readUTF(); // odczyt string
                ocena = raf.readDouble();
                
               //System.out.println(miejsce+" "+i+" "+s+" "+ocena);
              // textArea1.append(miejsce+" "+i+" "+s+" "+ocena+" \n");
                  textArea1.append(i+" "+s+" "+ocena+" \n");
               licz++;
            }
            while(raf.getFilePointer() < raf.length()  && licz <= ile);
            
            raf.close();
        }catch(IOException e){
            System.out.println("Błąd we/wy ");
       }
   }
    
    
   public  void popraw(int skok, double pocena){
           int i;
           String s;
           long miejsce;
           double ocena;
           
        try{
            RandomAccessFile raf = new RandomAccessFile("plik.bin", "rw");
            
           // raf.seek(skok); // skok -  adres w bajtach
           i=1;
           while(raf.getFilePointer() < raf.length() && i < skok){
                i = raf.readInt();
                s = raf.readUTF(); // odczyt string
                ocena =raf.readDouble();
                i++;
           } ;

                miejsce = raf.getFilePointer();
                i = raf.readInt();
                s = raf.readUTF(); // odczyt string
                raf.writeDouble(pocena);
                
            //   System.out.println(miejsce+" "+i+" "+s+" "+pocena);
         
            
            raf.close();
        }catch(IOException e){
            System.out.println("Błąd we/wy ");
       }
   }
   
    
    
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        textArea1 = new java.awt.TextArea();

        setLayout(null);
        add(textField1);
        textField1.setBounds(40, 60, 60, 30);
        add(textField2);
        textField2.setBounds(120, 60, 170, 30);
        add(textField3);
        textField3.setBounds(330, 60, 70, 30);

        label1.setText("Lp");
        add(label1);
        label1.setBounds(40, 30, 18, 20);

        label2.setText("Imie i nazwisko");
        add(label2);
        label2.setBounds(120, 30, 90, 20);

        label3.setText("Ocena");
        add(label3);
        label3.setBounds(330, 30, 40, 20);

        button1.setLabel("Dopisz");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(40, 130, 54, 24);

        button2.setLabel("Popraw");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(140, 130, 58, 24);

        button3.setLabel("Pokaż");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(260, 130, 49, 24);
        add(textArea1);
        textArea1.setBounds(30, 190, 580, 190);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        int i = Integer.parseInt(textField1.getText());
        String s = textField2.getText();
        double ocena = Double.parseDouble(textField3.getText());
                
       dopisz(i,s ,ocena );
       
       textField1.setText("");
       textField2.setText("");
       textField3.setText("");
       
       System.out.print("Zapisałem");
       
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
         
        odczyt(0, 100);
        
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        
        int i = Integer.parseInt(textField1.getText());
        String s = textField2.getText();
        double ocena = Double.parseDouble(textField3.getText());
                
        popraw(i, ocena);
        
       textField1.setText("");
       textField2.setText("");
       textField3.setText("");
       
       System.out.print("Poprawiłem");
        
    }//GEN-LAST:event_button2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
